### PR TITLE
Updated dependencies to use snapshot versions

### PR DESCRIPTION
**Pull request by inv-jishnu**
Updated project.clj file to use snapshot versions for scalardl-java-client-sdk.

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM

**Comment by feeblefakie** [comment]
@inv-jishnu CI fails. Please check and fix.

**Review by feeblefakie — COMMENTED** [review]
The CI fails.

**Comment by inv-jishnu** [comment]
@feeblefakie san
I will check and fix it.

**Comment by feeblefakie** [comment]
@inv-jishnu It's now fixed.

**Comment by feeblefakie** [comment]
@brfrn169 Can you take a quick look?

**Pull request merged**
