### PR TITLE
Add elle-append test

### PR DESCRIPTION
**Pull request by yito88**
To verify serializable transactions: https://scalar-labs.atlassian.net/browse/DLT-6513

The current Scalar DB (2.4.0) using snapshot isolation (also in the case using serializable) failed in this test because a transaction could read a different value after another transaction committed.
https://scalar-labs.atlassian.net/browse/DLT-7969

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! `jepsen.tests.cycle.append` looks really interesting!

Just a question. Tests with `jepsen.tests.cycle.wr` are also coming?

**Comment by yito88** [comment]
Thank you for reviewing.

> Tests with jepsen.tests.cycle.wr are also coming?

Ah, I didn't intend to add a test with `jepsen.tests.cycle.wr`. However, I'd like to add the test now since I could make the test with `append` earlier than I expected.

**Review by brfrn169 — APPROVED** [review]
I'll approve this, I don't understand it much though as I should not be a blocker. I'm studying Jepsen and Clojure to review this kind of PRs 😄

**Review by feeblefakie — APPROVED** [review]
LGTM!

**Pull request merged**
